public with sharing class Constants {
    public static final String apiOwnerName = 'Hello_Sign'; 
    public static final String signedStatusCode = 'Signed';
    public static final String sentForSignature = 'Sent to Driver';
    public static final String driverSignature = 'Driver Signed';
    public static final String adminSignature = 'Admin Signed';
    public static final String completeSignature = 'Completed';
    public static final String signatureRequest = 'Signature Request';
    public static final String driverAgreement = 'Driver Agreement';
    public static final String signedDocument = 'Signed Document';
    public final static String noApprovedYet = Label.Not_Approved_Yet_Mileage_Status;
    public final static String adminEmails = Label.Email_To_Address;

}