public with sharing class ContactDetails {
    public string accountName {get;set;}
    public string accountLogo {get;set;}
    public String contactName {get;set;}
    public string zipCode {get;set;}
    public string city {get;set;}
    public string state {get;set;}
    public string vehicalType {get;set;}
    public List<string> drivingStates {get;set;}
    public string fixedAmount {get;set;}
    public string compliancestatus {get;set;}
    public string carImage {get;set;}
    public string insuranceAttchId {get;set;}
    public string driverType {get;set;}
    public string annualReim {get;set;}
    public string annualMileages {get;set;}
    public string planInsurance {get;set;}
    public string complianceMileage {get;set;}
    public string planYears {get;set;}
    public string vehicleValue {get;set;}
    public string drivingState {get;set;}
    public date insuranceDate {get;set;}
    public string notimessage{get;set;}
    public string vehicleage{get;set;}
    public string vehiclevaluecheck{get;set;}
    public string mileagemeet {get;set;}
    public string insurance{get;set;}
    public string variableRate{get;set;}
    public boolean biWeekContact {get;set;}
}