@isTest
private class EmployeeReimbursements_Test {
    
    @isTest static void EmployeeReimburs() {
        EmployeeReimbursements obj = new EmployeeReimbursements();
        
        obj.employeeReimbursementId = 'a001h000001swsP';
        obj.variableRate = '1501.9167';
        obj.totalReimbursements = '1500.0000';
        obj.month = '02-2019';
        obj.intmonth = 02-2019;
        obj.status = 'Open';
        obj.isSelected = true;
        obj.maintainsAndTyres = 'maintainsAndTyres';
        obj.mpg = 'mpg';
        obj.fuel = '1.00';      
        obj.mileage = '10';
        obj.approveddate = '05/12/19';
        obj.varibleAndFixedReimbursements = '1.00';
        obj.varibleAmount = '1.00';
        obj.fixed1 = '1.00';
        obj.fixed2 = '1.00';
        obj.fixed3 = '1.00';
        obj.totalFixedAmount = '1.00';
        obj.contactEmail = 'abc@gmail.com';
        obj.contactdrivertype = 'driver-fulltime';
    }  
}