@isTest
public class EmployeeMileagesForCalculation_Test {
    @isTest
        public static void testMethod1() {
        EmployeeMileagesForCalculation obj = new EmployeeMileagesForCalculation();
        obj.reimbursementid  = 'a001h000001swsP';
        obj.mileageid = 'a002h000001swsP';
        obj.contactid = 'a003h000001swsP';
        obj.name = 'test';
        obj.month = '02-2019';
        obj.threshold = '20';
        obj.totalMileages ='250';
        obj.approvedMileages = '12';
        obj.isSelected = true;
        obj.managerName = 'Doris';
        obj.isSelectedEmailReminder = true;
        obj.mileageApproval = 'Minkesh';
        obj.managerEmail = 'test@gmail.com';
        obj.reimbursementApproval = true;
        obj.status = 'Approve';
        obj.lockDate = String.valueOf(System.today());
        obj.rejectedMileges = '30';   
		obj.rejectedMileages = '40';   
        obj.totalHighRiskMileages = 34.3; 
        obj.highRiskTotalApproved = 34.3; 
        obj.highRiskTotalRejected = 34.3; 
    }
}