public with sharing class EmployeeMileages 
{    
    public string maintTyre {get;set;}
    public string fuelRate {get;set;}
    public boolean isSelected {get;set;}
    public boolean isChecked {get;set;}
    public boolean isUnapprove {get;set;}
    public String tripdate {get;set;}
    public String dayofweek {get;set;}
    public String starttime {get;set;}
    public String endtime {get;set;}
    public String status {get;set;}
    public String origin {get;set;}
    public String originname {get;set;}
    public String originalOriginName {get;set;}
    public String OriginalDestinationName {get;set;}
    public String destination {get;set;}
    public String destinationname {get;set;}
    public String mileage {get;set;}
    public String variableamount{get;set;}
    public String totalMonthlyApproveVariable {get; set;}
    public String variablerate{get;set;}
    public String approveddate{get;set;}
    public String submitteddate {get;set;}
    public String reimbursementid {get;set;}
    public String month {get;set;}
    public String driverid {get;set;}
    public String totalpending {get;set;}
    public String tracingstyle {get;set;}
    public String emailaddress {get;set;}
    public String totalMileages {get;set;}
    public String totalrejected {get;set;}
    public String notes {get;set;}
    public String tag {get;set;}
    public String id {get;set;}
    public String lockdate {get;set;}
    public boolean isLockDate {get;set;}
    public String staytime {get;set;}
    public String drivingtime {get;set;}
    public String totaltime {get;set;}
    public String tripActivity {get;set;}
    public String halfFixedAmount {get; set;}
    public String fuelVariableRate{get; set;}
    public String approvalName{get; set;}
    public String fromLocation{get; set;}
    public String toLocation{get; set;}
    public datetime startdatetime{get; set;}
    public datetime enddatetime{get; set;}
    public boolean highRiskMileage{get; set;}
    public String originalReimbursementid {get;set;}
    public EmployeeMileages() 
    {
        
    }
}