@isTest
public class EmployeeMileagestest {
    public static testmethod void EmployeeMileagesTestMethod() {
        Test.startTest();
            EmployeeMileages em = new EmployeeMileages();
            em.isSelected = false;
            em.isChecked = false;
            em.tripdate = '';
            em.status = '';
            em.origin = '';
            em.destination = '';
            em.mileage = '';
            em.variableamount = '';
            em.variablerate = '';
            em.approveddate = '';
            em.submitteddate = '';
            em.reimbursementid = '';
            em.month = '';
            em.driverid = '';
            em.id = '';
            em.dayofweek='';
            em.endtime ='';
            em.tracingstyle='';
            em.emailaddress='';
            em.totalpending ='';
            em.totalrejected ='';
            em.totalpending ='';
            em.destinationname='';
            em.originname='';
            em.starttime='';
            em.fuelRate='';
            em.maintTyre='';
            em.totalMileages='';
            em.lockdate = '';
            em.isLockDate = false;
            em.staytime = '';
            em.drivingtime = '';
            em.totaltime = '';
            em.tripActivity = '';
            em.halfFixedAmount = '';
            em.fuelVariableRate = '';
            em.approvalName = '';
        Test.stopTest();
    }
}