@isTest
public class TrueDialogVfPageControllerTest {
	static testMethod void testMethod1() {
        
        
	/*	
         Account a = TestDataFactory.createAccount(false, 'demo', false);
        a.True_Dialog__c = true;
        insert a;

        Contact c  = TestDataFactory.createCICDContact(false, a.id);
        
        c.email = 'test2222@gmail.com';
        c.MobilePhone = '+13239538840';
        c.lastName = 'Veer';
        c.firstName = 'Sharma';
        c.External_Email__c = 'test222@gmail.com';
        
        insert c;
        
		ApexPages.StandardController sc = new ApexPages.StandardController(a);
        TrueDIalogVFPageController obj = new TrueDIalogVFPageController(sc);
        
        
        PageReference pageRef = Page.TrueDialog; // Add your VF page Name here
        pageRef.getParameters().put('id', String.valueOf(a.Id));
        Test.setCurrentPage(pageRef);*/
        
        
        
        
    }
}