public with sharing class WrapperTaxReport {
    public WrapperTaxReport() {
        
    }
    public String drivername {get;set;}
    public String employeeid {get;set;}
    public String emailid {get;set;}
    public Double approvedmileages {get;set;}
    public Double totalreim {get;set;}
    public Double iRSallowable {get;set;}
    public Double imputedincome {get;set;}
    public Integer month {get;set;}
    public String year {get;set;}
    public String monthyear {get;set;}      
    public Double variableRate {get;set;}      
}